### ISSUE TITLE
Fichier log un poil plus lisible.

### ISSUE THREAD

**Issue by ebugnet** [patrickpollet/moodle_local_ldap#1]
Salut Patrick,
Serait-il simplement possible de faire en sorte qu'il y ait un retour à la ligne sur le fichier de log ?
Ca sera bien plus lisible comme ça !
Merci,
Eric

**Comment by patrickpollet** [comment]
Salut Eric,

```
 et portant j'ai fait attention de bien utiliser la constante PHP_EOL de partout.
```

Tu es surement sous Windows pour lire le log ? Peut tu utiliser un éditeur moins 'basique' que notepad
ça devrait arranger le coup ...
A+

**Comment by ebugnet** [comment]
Meaculpa !
En effet, j'avais pas fait attention au programme par défaut.
Merci...

Bon, me reste plus qu'a trouver les bonnes variables...
Eric
